# Generated by Django 2.2.3 on 2019-07-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_id', models.IntegerField(max_length=500, primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('User_name', models.CharField(max_length=150)),
                ('Date_of_Birth', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_no', models.BigIntegerField()),
                ('Password', models.CharField(max_length=128)),
                ('RPassword', models.CharField(max_length=128)),
            ],
        ),
    ]
