# Generated by Django 2.2.3 on 2019-07-29 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='Token',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='token',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.Users'),
        ),
    ]
