# Generated by Django 2.2.3 on 2019-07-29 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20190729_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='User_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
