# Generated by Django 2.2.3 on 2019-07-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20190729_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='RPassword',
        ),
        migrations.AddField(
            model_name='users',
            name='Gender',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
