# Generated by Django 2.2.3 on 2019-07-29 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20190729_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='Token',
            new_name='Tokens',
        ),
    ]
